title: CIE A Level Physics & Maths Resources # Change this
email: your-email@example.com # Change this
description: >- # Change this
  A comprehensive resource for Cambridge International AS & A Level
  Physics (9702) and Mathematics (9709) students, designed for the
  2025, 2026, and 2027 examinations.
baseurl: "" # The subpath of your site, e.g., /blog
url: "[https://your-username.github.io](https://your-username.github.io)" # the base hostname & protocol for your site, e.g. [http://example.com](http://example.com)
github_username:  your-username # Change this

# Build settings
markdown: kramdown
theme: null # Remove the default theme.
# Outputting the same file name
permalink: /:title/
paginate: 5 # Optional: For paginating blog posts
paginate_path: "/page:num/" # Optional: For paginated pages

# Plugins
plugins:
  - jekyll-feed # For generating an RSS feed
  - jekyll-sitemap # For generating a sitemap.xml
  - jekyll-seo-tag # For better SEO
#  - jekyll-search # Uncomment to add search, requires additional setup

# Exclude from processing.
# The following items will not be processed, by default.
# Keep this list intact until you know what you're doing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Add any other configuration here
sass:
  sass_dir: _sass # The directory where your Sass files are located